pull_request_rules:
  - name: auto merge for hash fix
    conditions:
      - and:
        - author=github-actions[bot]
        - title~=^.*Fix hash$
        - or:
          - check-success=Test Manifests / Powershell 5 (push)
          - check-success=Test Manifests / Powershell 5 (pull_request)
    actions:
      merge:
        method: squash
