on:
  issue_comment:
    types: [created]
name: Pull requests comment
jobs:
  pullRequestHandler:
    name: PullRequestHandler
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@master
    - name: PullRequestHandler
      uses: Ash258/Scoop-GithubActions@stable-win
      if: startsWith(github.event.comment.body, '/verify')
      env:
        SHOVEL: '1'
        GITH_EMAIL: hoilc@foxmail.com
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
